#!/bin/bash

if [ "$#" -eq 0 ];
then echo "Input file required";
else
for arg in $@ ; do
echo "title~views~since_upload">$arg'.csv'
grep -Eoz "\"=?v=?i=?d=?e=?o=?-=?t=?i=?t=?l=?e=?-=?l=?i=?n=?k=?\"[^>]*>" $arg|
tr -d '\000'|
sed -E 's/[~\t]//g'|
tr '\n' '~'|
sed -E 's/=?~//g'|
tr '>' '\n'|
sed -E "s/.*aria-label=3D\"([^\"]*)\"/\1/g"|
#tr '\t' '\n'>>$arg'.csv';
done;
fi
