#!/bin/bash

if [ "$#" -eq 0 ];
then echo "Input file required";
else
	for arg in $@ ; do
		grep -oHEm 1 "(([0-9]{2}\.[0-9])|([0-9]{2,3}))M subscriber" $arg | sed -E "s~([^/]+/)*([^ ]+) subscriber~\2~" |sed -E "s/(([-_][0-9]{1,2}){3}\.mht(ml)?):/~/; s/^([0-9]+)_/\1~/"
	done;
fi
