#!/bin/bash

if [ "$#" -eq 0 ];
then echo "Input file required";
else
	match_timeunits="[ymwdhms][eoaoi][aneyunc][rksruo]?[shtn]?[sed]?[s]?"
	today=$(date +"%m-%d-%y")
	invalid_dump="collected_invalids"
	rm $invalid_dump
	touch $invalid_dump
	start_time="$(date +%s%3N)"
	for arg in $@ ; do
		echo "Interpretting: $arg..."
		python3 interpret-dates.py $today $arg $invalid_dump
	done;
	echo "$[ ( $(date +%s%3N) - ${start_time} ) ]" | 
		awk '{time = $1 / 1000;printf "total run: %.3fs\n", time }'
fi
